### ISSUE TITLE
Ability to log useful statistics about questions and groups for later evaluation

### ISSUE THREAD

**Issue by lmc64** [DukeLearningInnovation/nudge#23]
Not quite sure what we would be logging, @profmikegreene @hrvalli can you clarify or give some examples?

**Comment by hrvalli** [comment]
I believe we mean logging student answers to questions (disassociated from student identities). So if out of100 students, 10 answer a, 50 answer b, 25 answer c, and 15 answer d, we'd get the overall percentages of answer choices (a=10% b=50% etc.).

**Comment by lmc64** [comment]
Okay that makes sense. Thanks for the clarification!
